import Head from 'next/head'

export default function Header(){
    return (
        <Head>
            <title>SIAKAD UNAND</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/logo.ico" />
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"></link>
        </Head>
    )
}